destination: _site/
url: "http://127.0.0.1:4011"
baseurl: "/service1-pdf"
port: 4011
product: Service1
print_title: Service1 documentation
print_subtitle: version 1.0
output: pdf
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page_print"
      comments: true
      search: true

pdf_sidebar: service1_sidebar
